### ISSUE TITLE
Control delay in example JSON produces an error

### ISSUE THREAD

**Issue by blairjordan** [jmartin82/mmock#113]
Using `/config/delay.json` I encounter:
```
2020/05/01 07:07:16 Invalid mock format in: /config/delay.json Err: json: cannot unmarshal string into Go struct field Control.delay of type int
```

Updated:
```
    "control": {
        "delay": "400ms"
    }
```
to:
```
    "control": {
        "delay": 4
    }
```

Fixes the issue.

**Comment by jmartin82** [comment]
Hi!

Thanks for reporting an issue! 

Can you specify the version where you see this problem?

It seems an new example running on a old mmock versions, could it be?
