### ISSUE TITLE
Parallel execution

### ISSUE THREAD

**Issue by tasomaniac** [jmartin82/mmock#124]
Hi, we have mmock deployed to a server. We use it to run our tests against it. When 2 test executions run in parallel, we started to see flakiness. This is basically because they share the same state and mess up with each other. 

Do you have any suggestion to support parallel execution with state management?

**Comment by jmartin82** [comment]
Hey, the only solution that came to my mind is to add some response header like "X-MMOCK-SCENARIO" and append this header value to the following request to identify the current scenario, this will imply some development in mmock,  but will force you to create specific code for a test that it's far from ideal...

To really keep it isolated, I think the only way to go it is to have more than one instance of mmock, one for each execution parallel process.

**Comment by tasomaniac** [comment]
In case we want to go for multiple deployment path, is there an easy way to figure out how to deal with distribution of available services?

**Comment by jmartin82** [comment]
Hey, sorry for this late answer.

I don't know the details of your implementation, but maybe this calls (https://github.com/jmartin82/mmock#mapping
) can help you to discover any service available.

Another option could be to have duplicate mmock instances with the same services and just adjust the distribution of the test and set up the mock endpoint using the env vars of your CI platform.


``` 
                                           ┌─────────┐
        ┌──────────────┐   mmock:8082      │         │
        │   Test 1     ├──────────────────►│ Mmock   │
        └──────────────┘                   │         │
                                           └─────────┘
        ┌──────────────┐   mmock:8082        ▲
        │   Test 2     ├─────────────────────┘
        └──────────────┘




                                           ┌─────────┐
        ┌─────────────┐   mmock-1:8082     │         │
        │  Test 1     ├────────────────────┤  mmock  │
        └─────────────┘                    └─────────┘
Env: Node_1
────────────────────────────────────────────────────────────

        ┌─────────────┐   mmock-2:8082     ┌─────────┐
        │  Test2      ├───────────────────►│  mmock  │
        └─────────────┘                    │         │
                                           └─────────┘
Env: Node_2 ´´´
