### ISSUE TITLE
`proxyBaseUrl` + `crazy` or `delay` -- doesn't seem to be working

### ISSUE THREAD

**Issue by briantist** [jmartin82/mmock#125]
When I use `proxyBaseUrl`, setting `crazy: true` or setting a `delay` doesn't work. The proxying part works but it never returns a 500 and isn't delayed.

Is there a way to get these features working together?

**Comment by jmartin82** [comment]
Fixed in this PR https://github.com/jmartin82/mmock/pull/137 

Thanks for reporting it.

**Comment by briantist** [comment]
amazing! thanks so much for this
