### ISSUE TITLE
Read json response from a file.

### ISSUE THREAD

**Issue by RaviH** [jmartin82/mmock#48]
I have a file with large json. I would like to be able to read the file from file path instead of pasting the entire response json in config.

**Comment by jmartincmp** [comment]
I like the idea.

Any suggestion about how to express that with the mmock DSL?

`body:"file://xxx"` or `bodyFileName: "xxx"`, more  options ?

**Comment by Nekroze** [comment]
I think a different field for this is warranted.

**Comment by jmartin82** [comment]
Added finally with as a new tag. It seems more flexible to me.
https://github.com/jmartin82/mmock/blob/master/config/big-payload.json
