### ISSUE TITLE
mmock on Windows 10 host: View and Edit buttons in the Console Mapping Tab return 404 Not Found

### ISSUE THREAD

**Issue by heresandyboy** [jmartin82/mmock#53]
MMock v 2.0.2
Windows 10 
go version go1.10.1 windows/amd64

Hi, 
First attempt with Mmock today, I have installed via go and created a config directory.

I run the command
`mmock -config-path "mmock-config"`

The console runs at 10.128.3.102:8082, but the View and Edit buttons in the mapping tab return 404:
`GET http://10.128.3.102:8082/api/mapping//hello.json 404 (Not Found)`

In the config directory I have the following basic sample:

hello.json
```
{
	"request": {
		"method": "GET",
		"path": "/hello/*"
	},
	"response": {
		"statusCode": 200,
		"headers": {
			"Content-Type":["application/json"]
		},
		"body": "{\"hello\": \"{{request.query.name}}, my name is {{fake.FirstName}}\"}"
	}
}
```

Additionally, where is the actual http server running by default, I'd assumed on a Port on 127.0.0.1 but the terminal output does not specify:

```
2018/04/24 17:34:11 Getting external IP
2018/04/24 17:34:11 File monitor started
2018/04/24 17:34:11 HTTP Server running at 10.128.3.102:8083
2018/04/24 17:34:11 HTTPS Server running at 10.128.3.102:8084
2018/04/24 17:34:11 Console running at 10.128.3.102:8082
2018/04/24 17:34:11 TLS certificates not found, impossible to start the TLS server.
```
I am genuinely excited about the possibilities for our team using your tool, hopefully with a little help perhaps I could do a little getting started guide for complete noobs like me (first time using Go too!)

![mmock 404 errors](https://user-images.githubusercontent.com/553990/39202561-280df298-47ea-11e8-9219-3d850479a607.PNG)

**Comment by heresandyboy** [comment]
Thank you that would be much appreciated, I'd spent some time looking over the source to see if I could contribute, I'm afraid I'm out of my depth for now.

My actual use case will be to mock out dependencies for integration tests as part of our CI/CD, being able to deploy an exe and some json config for use in the test pipeline would be a wonderfully simple and versatile solution. 

I have tried running mmock via docker on my Win10 dev machine, but unfortunately I am unable to browse to the ip/port combinations from my host. I have not been able to figure out why, though I do have other webservices running in docker that I am able to ping and browse successfully.

I'm 'fairly' confident with docker, I have a few things running locally. I was able to set it up easily with your docker file:

```
docker build -t mmock/mmock .
docker run -v 'C:/Users/USERNAME/Docker/apps/mmock':'/config' -p 8082:8082 -p 8083:8083  mmock/mmock
```
```
2018/04/25 12:56:11 File monitor started
2018/04/25 12:56:11 Loading config file: /config/config/hello.json
2018/04/25 12:56:11 HTTP Server running at 172.17.0.2:8083
2018/04/25 12:56:11 HTTPS Server running at 172.17.0.2:8084
2018/04/25 12:56:11 Console running at 172.17.0.2:8082
2018/04/25 12:56:11 Loading X509KeyPair (server.crt/server.key)
2018/04/25 12:56:18 Changes detected in mock definitions  FILE "hello.json" WRITE [/config/config/hello.json]
2018/04/25 12:56:18 Loading config file: /config/config/hello.json
```
`docker inspect CONTAINERNAME` shows that the ports and IPs are all set up 


```
"ExposedPorts": {
                "8082/tcp": {},
                "8083/tcp": {},
                "8084/tcp": {}
            },
```
...
```
 "Ports": {
                "8082/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8082"
                    }
                ],
                "8083/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8083"
                    }
                ],
                "8084/tcp": null
            },
```
...
```
"Gateway": "172.17.0.1",
"IPAddress": "172.17.0.2",
"IPPrefixLen": 16,
```

If anyone has any ideas please let me know, I'm pressed for time (aren't we all) to come up with a prototype solution to our http mocking needs, I am going to check out some other solutions for comparison anyway, my initial investigations have lead me to mmock and I like what I see, keep up the good work!

**Comment by jmartin82** [comment]
Win10 version fixed and released here: https://github.com/jmartin82/mmock/releases/tag/v2.2.0

Let me know how it works.

About your use case, make sense, I'm using it too in the same way in our CI/CD process and it works like a charm :-)

**Comment by jmartin82** [comment]
About your issues with docker. It seems the mmock is not able to bind the sockets with a public IP inside docker.

```
2018/04/25 12:56:11 HTTP Server running at 172.17.0.2:8083
2018/04/25 12:56:11 HTTPS Server running at 172.17.0.2:8084
2018/04/25 12:56:11 Console running at 172.17.0.2:8082
```

It's really easy to fix, I've added a CMS with this default parameters `CMD ["-server-ip","0.0.0.0","-console-ip","0.0.0.0"]`

I haven't had this problem before, because I usually extend the image adding my own mocks and tweaking the entry point, before pushing it into a private repo.

But anyways if you pull the last docker image, should work without problems.
