### ISSUE TITLE
Incorrect install section via Docker

### ISSUE THREAD

**Issue by Carsak** [jmartin82/mmock#74]
Hi
Install section is incorrect
**Current:**
```
go get github.com/jmartin82/mmock
docker build -t mmock/mmock .
docker run -v YOUR_ABS_PATH:/config -p 8082:8082 -p 8083:8083  mmock/mmock
```

**Why**
No need 
go get github.com/jmartin82/mmock
Error on docker build -t mmock/mmock .
no such file or directory

**Actual**
1. sudo docker image pull jordimartin/mmock
2. sudo docker run -v YOUR_ABS_PATH:/config -p 8082:8082 -p 8083:8083  jordimartin/mmock

thats all

![image](https://user-images.githubusercontent.com/9497934/48995797-a06f9380-f173-11e8-8778-a984e41a9428.png)

**Comment by jmartin82** [comment]
Fixed on 0df601f

Thanks!!
