### ISSUE TITLE
Error while install "Cant load package: ..... no Go files in ...."

### ISSUE THREAD

**Issue by Carsak** [jmartin82/mmock#82]
go version 1.10.4
![image](https://user-images.githubusercontent.com/9497934/58168416-06b31a00-7cb0-11e9-854c-49832148ec17.png)

Error while install
go get github.com/jmartin82/mmock
![image](https://user-images.githubusercontent.com/9497934/58168494-3b26d600-7cb0-11e9-8419-a5a62db20c35.png)
 "Cant load package: package github.com/jmartin82/mmock: no Go files in ...."

List of files in path go/src/github.com/jmartin82/mmock/
![image](https://user-images.githubusercontent.com/9497934/58168620-88a34300-7cb0-11e9-8258-0fe31ccf01a7.png)

go env
![image](https://user-images.githubusercontent.com/9497934/58168685-a5d81180-7cb0-11e9-8f44-04d043dcc7be.png)

**Comment by jmartin82** [comment]
Hey, I forgot to update the documentation after the last project layout refactor.
This command `github.com/jmartin82/mmock/...` should work.

I'm updating the documentation
