### ISSUE TITLE
Typo in mmock/config/crud/users-get.json

### ISSUE THREAD

**Issue by Carsak** [jmartin82/mmock#83]
typo in https://github.com/jmartin82/mmock/blob/dc84d6fd6d34602d7c8d7567ac6c3a1bb0a73b48/config/crud/users-get.json#L14

Must be: 
"body": "{\"id\":\"{{request.path.userid}}\",\"name\":\"Leanne Graham\",\"username\":\"Bret\",\"email\": \"Sincere@april.biz\",\"address\":{\"street\": \"Kulas Light\",\"suite\": \"Apt. 556\",\"city\": \"Gwenborough\",\"zipcode\": \"92998-3874\"}}"

Remove 1 brace in the end

**Comment by jmartin82** [comment]
You are completely right!

Fixed: https://github.com/jmartin82/mmock/commit/7e3041d70f5d94ac475b8349bbbb537f92f5a408
