### ISSUE TITLE
Inccorect url in readme, 404 in /statistics/statistics.go 

### ISSUE THREAD

**Issue by Carsak** [jmartin82/mmock#84]
Line in readme
_Mmock is collecting anonymous statistics about the usage of the following actions:
Source code: /statistics/statistics.go_

Url /statistics/statistics.go redirect to 
https://github.com/jmartin82/mmock/blob/master/statistics/statistics.go#L30

Error 404 not found

**Comment by jmartin82** [comment]
Thanks a lot 👏 

Fixed: https://github.com/jmartin82/mmock/commit/01e389cdab562be6fa625b41da263606a1a79982
