### ISSUE TITLE
How to clear all scenarios?

### ISSUE THREAD

**Issue by Carsak** [jmartin82/mmock#85]
Readme says:
_Scenario
Title : Clean all scenarios status and pause state.
URL : /api/scenarios/reset_all
Method : GET
Response Codes: Success (200 OK)_

I call like
GET
http://localhost:8083/api/scenarios/reset_all
but got 404 not found

![image](https://user-images.githubusercontent.com/9497934/58229776-606d2000-7d54-11e9-824c-2aedb5b7054f.png)

**Comment by jmartin82** [comment]
For any API call, you should use the console endpoint. 

By default: IP:8082

Thanks,

**Comment by Carsak** [comment]
ow, thanks
For others, more detail in swagger.json doc
https://github.com/jmartin82/mmock/blob/master/tmpl/swagger.json
