### ISSUE TITLE
Get `internal` packages back into public scope

### ISSUE THREAD

**Issue by steirico** [jmartin82/mmock#86]
Hi,

I'm thinking about integrating mmock in our testing and CI/CD framework and to launch the mmock server (dispatcher) in-process.

As far as I like the refactoring introduced in 97bd7680798c0d95be560dc7ec95a100e32f31b7 it prevents reusing the project in external code since the most relevant packages are `internal`.

Any chance to have these `internal` packages back in a public scope?

Cheers, steirico

**Comment by jmartin82** [comment]
Sure, right now the public `pkg` contains all the logic to matching request and their mocks, but I'm completely open to moving anything else there that can be useful or necessary. Just let me know what you need or send me a PR with the change.

**Comment by steirico** [comment]
Good to hear that...

I will evaluate our needs and will get back.

Thanks a lot!

**Comment by jmartin82** [comment]
I'm going to close it, feel free to reopen it if you have a proposal.

Thanks,
