### ISSUE TITLE
Reading an array of json as a body payload fails

### ISSUE THREAD

**Issue by joel-44** [jmartin82/mmock#88]
When having the body payload as an array of json objects this error is happening: 
"Err: json: cannot unmarshal array into Go value of type definition.Mock". 

For example this would fail:

`[{"name":"bob","age":35"} , {"name":"john","age":30"}]`

**Comment by jmartin82** [comment]
Fixed https://github.com/jmartin82/mmock/commit/1878ed607a714b334aad6a5ac82df4e758dfb7cc ! Thanks for your help 👍
