### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by fan0412** [jmartin82/mmock#99]
StressTest , Memory Leak
![image](https://user-images.githubusercontent.com/41898733/74742482-a6322700-5299-11ea-849c-6b32eb61ea82.png)

**Comment by jmartin82** [comment]
Hi! Mmock stores by default all the transactions in memory to allow the users to check previous matches. You always can clean the stored transactions using the following endpoint:

https://github.com/jmartin82/mmock#verify

`/api/request/reset`

Anyway, I will provide an eviction configuration to prevent Mmock stops running by this issue.

**Comment by jmartin82** [comment]
This version https://github.com/jmartin82/mmock/releases/tag/v2.7.6 should fix your problem. Thanks for reporting it.
